services:
  TEMPLATE_SERVICE_NAME:
    build:
      context: ../
      dockerfile: docker-compose/Dockerfile
    image: gustavo0426/TEMPLATE_IMAGE_NAME:latest
    container_name: TEMPLATE_CONTAINER_NAME
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - TEMPLATE_SERVICE_NAME_network
    depends_on:
      - TEMPLATE_SERVICE_NAME-db

  TEMPLATE_SERVICE_NAME-db:
    image: postgres:16-alpine
    container_name: db-TEMPLATE_SERVICE_NAME
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - TEMPLATE_SERVICE_NAME_network
      - shared_pgadmin_network
    volumes:
      - TEMPLATE_SERVICE_NAME_TEMPLATE_MOTOR_DATABASE_data:/var/lib/postgresql/data

networks:
  TEMPLATE_SERVICE_NAME_network:
    name: TEMPLATE_SERVICE_NAME_network
    driver: bridge
  shared_pgadmin_network:
    external: true

volumes:
  TEMPLATE_SERVICE_NAME_TEMPLATE_MOTOR_DATABASE_data:
    name: TEMPLATE_SERVICE_NAME_TEMPLATE_MOTOR_DATABASE_data
